server:
  port: 8084

spring:
  datasource:
    url:  jdbc:oracle:thin:@100.125.120.56:1521:XE
    username: HANDYSERVE
    password: handyserve123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.OracleLegacyDialect
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.OracleLegacyDialect
        default_schema: HANDYSERVE
  data:
    mongodb:
      uri: mongodb+srv://Handyserve:s6B2aEMgJmo6kjb7@handyserve-cluster.8kdketu.mongodb.net/handyserve?retryWrites=true&w=majority&appName=handyserve-cluster
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

jwt:
  secret: handyserve_super_secret_key_for_jwt_minimum_256_bits_change_in_prod
  expiration-ms: 900000
  refresh-expiration-ms: 604800000

app:
  auth-service-url: http://localhost:8082
client-origin: ${APP_CLIENT_ORIGIN:https://handyserve.vercel.app}
  nominatim-base: https://nominatim.openstreetmap.org

management:
  endpoints:
    web:
      exposure:
        include: health,info
